// source: proto/entities/truck_state_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_entities_truck_pb = require('../../proto/entities/truck_pb.js');
goog.object.extend(proto, proto_entities_truck_pb);
goog.exportSymbol('proto.pb.TruckStateMessage', null, global);
goog.exportSymbol('proto.pb.TruckStateMessage.State', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.TruckStateMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.TruckStateMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.TruckStateMessage.displayName = 'proto.pb.TruckStateMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.TruckStateMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.TruckStateMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.TruckStateMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.TruckStateMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    truckError: (f = msg.getTruckError()) && proto_entities_truck_pb.Truck.toObject(includeInstance, f),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.TruckStateMessage}
 */
proto.pb.TruckStateMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.TruckStateMessage;
  return proto.pb.TruckStateMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.TruckStateMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.TruckStateMessage}
 */
proto.pb.TruckStateMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_entities_truck_pb.Truck;
      reader.readMessage(value,proto_entities_truck_pb.Truck.deserializeBinaryFromReader);
      msg.setTruckError(value);
      break;
    case 2:
      var value = /** @type {!proto.pb.TruckStateMessage.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.TruckStateMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.TruckStateMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.TruckStateMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.TruckStateMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTruckError();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_entities_truck_pb.Truck.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.pb.TruckStateMessage.State = {
  UNKNOWN_STATE: 0,
  UPLOAD: 1,
  DOWNLOAD: 2,
  TO_UPLOAD: 3,
  TO_DOWNLOAD: 4,
  WAITING: 5,
  QUEUE: 6
};

/**
 * optional Truck truck_error = 1;
 * @return {?proto.pb.Truck}
 */
proto.pb.TruckStateMessage.prototype.getTruckError = function() {
  return /** @type{?proto.pb.Truck} */ (
    jspb.Message.getWrapperField(this, proto_entities_truck_pb.Truck, 1));
};


/**
 * @param {?proto.pb.Truck|undefined} value
 * @return {!proto.pb.TruckStateMessage} returns this
*/
proto.pb.TruckStateMessage.prototype.setTruckError = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.TruckStateMessage} returns this
 */
proto.pb.TruckStateMessage.prototype.clearTruckError = function() {
  return this.setTruckError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.TruckStateMessage.prototype.hasTruckError = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional State state = 2;
 * @return {!proto.pb.TruckStateMessage.State}
 */
proto.pb.TruckStateMessage.prototype.getState = function() {
  return /** @type {!proto.pb.TruckStateMessage.State} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.pb.TruckStateMessage.State} value
 * @return {!proto.pb.TruckStateMessage} returns this
 */
proto.pb.TruckStateMessage.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


goog.object.extend(exports, proto.pb);
