// source: proto/entities/truck.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_entities_contractor_pb = require('../../proto/entities/contractor_pb.js');
goog.object.extend(proto, proto_entities_contractor_pb);
var proto_enums_event_state_enums_pb = require('../../proto/enums/event_state.enums_pb.js');
goog.object.extend(proto, proto_enums_event_state_enums_pb);
var proto_entities_event_state_pb = require('../../proto/entities/event_state_pb.js');
goog.object.extend(proto, proto_entities_event_state_pb);
var proto_entities_sensor_pb = require('../../proto/entities/sensor_pb.js');
goog.object.extend(proto, proto_entities_sensor_pb);
var proto_entities_excavator_pb = require('../../proto/entities/excavator_pb.js');
goog.object.extend(proto, proto_entities_excavator_pb);
var proto_entities_load_pb = require('../../proto/entities/load_pb.js');
goog.object.extend(proto, proto_entities_load_pb);
goog.exportSymbol('proto.pb.OperationAssignmentUnit', null, global);
goog.exportSymbol('proto.pb.OperationAssignmentUnit.Shift', null, global);
goog.exportSymbol('proto.pb.OperationAssignmentUnit.State', null, global);
goog.exportSymbol('proto.pb.Truck', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.OperationAssignmentUnit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.OperationAssignmentUnit.repeatedFields_, null);
};
goog.inherits(proto.pb.OperationAssignmentUnit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.OperationAssignmentUnit.displayName = 'proto.pb.OperationAssignmentUnit';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.Truck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.Truck.repeatedFields_, null);
};
goog.inherits(proto.pb.Truck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.Truck.displayName = 'proto.pb.Truck';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.OperationAssignmentUnit.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.OperationAssignmentUnit.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.OperationAssignmentUnit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.OperationAssignmentUnit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.OperationAssignmentUnit.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    excavator: (f = msg.getExcavator()) && proto_entities_excavator_pb.Excavator.toObject(includeInstance, f),
    truckList: jspb.Message.toObjectList(msg.getTruckList(),
    proto.pb.Truck.toObject, includeInstance),
    upload: (f = msg.getUpload()) && proto_entities_load_pb.Upload.toObject(includeInstance, f),
    download: (f = msg.getDownload()) && proto_entities_load_pb.Download.toObject(includeInstance, f),
    shift: jspb.Message.getFieldWithDefault(msg, 6, 0),
    state: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.OperationAssignmentUnit}
 */
proto.pb.OperationAssignmentUnit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.OperationAssignmentUnit;
  return proto.pb.OperationAssignmentUnit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.OperationAssignmentUnit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.OperationAssignmentUnit}
 */
proto.pb.OperationAssignmentUnit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto_entities_excavator_pb.Excavator;
      reader.readMessage(value,proto_entities_excavator_pb.Excavator.deserializeBinaryFromReader);
      msg.setExcavator(value);
      break;
    case 3:
      var value = new proto.pb.Truck;
      reader.readMessage(value,proto.pb.Truck.deserializeBinaryFromReader);
      msg.addTruck(value);
      break;
    case 4:
      var value = new proto_entities_load_pb.Upload;
      reader.readMessage(value,proto_entities_load_pb.Upload.deserializeBinaryFromReader);
      msg.setUpload(value);
      break;
    case 5:
      var value = new proto_entities_load_pb.Download;
      reader.readMessage(value,proto_entities_load_pb.Download.deserializeBinaryFromReader);
      msg.setDownload(value);
      break;
    case 6:
      var value = /** @type {!proto.pb.OperationAssignmentUnit.Shift} */ (reader.readEnum());
      msg.setShift(value);
      break;
    case 7:
      var value = /** @type {!proto.pb.OperationAssignmentUnit.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.OperationAssignmentUnit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.OperationAssignmentUnit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.OperationAssignmentUnit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.OperationAssignmentUnit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExcavator();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_entities_excavator_pb.Excavator.serializeBinaryToWriter
    );
  }
  f = message.getTruckList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.pb.Truck.serializeBinaryToWriter
    );
  }
  f = message.getUpload();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto_entities_load_pb.Upload.serializeBinaryToWriter
    );
  }
  f = message.getDownload();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto_entities_load_pb.Download.serializeBinaryToWriter
    );
  }
  f = message.getShift();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.pb.OperationAssignmentUnit.Shift = {
  UNKNOWN_SHIFT: 0,
  NIGHT: 1,
  DAY: 2
};

/**
 * @enum {number}
 */
proto.pb.OperationAssignmentUnit.State = {
  UNKNOWN_STATE: 0,
  PENDING: 1,
  OPENED: 2,
  CLOSED: 3
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.pb.OperationAssignmentUnit.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.OperationAssignmentUnit} returns this
 */
proto.pb.OperationAssignmentUnit.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Excavator excavator = 2;
 * @return {?proto.pb.Excavator}
 */
proto.pb.OperationAssignmentUnit.prototype.getExcavator = function() {
  return /** @type{?proto.pb.Excavator} */ (
    jspb.Message.getWrapperField(this, proto_entities_excavator_pb.Excavator, 2));
};


/**
 * @param {?proto.pb.Excavator|undefined} value
 * @return {!proto.pb.OperationAssignmentUnit} returns this
*/
proto.pb.OperationAssignmentUnit.prototype.setExcavator = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.OperationAssignmentUnit} returns this
 */
proto.pb.OperationAssignmentUnit.prototype.clearExcavator = function() {
  return this.setExcavator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.OperationAssignmentUnit.prototype.hasExcavator = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Truck truck = 3;
 * @return {!Array<!proto.pb.Truck>}
 */
proto.pb.OperationAssignmentUnit.prototype.getTruckList = function() {
  return /** @type{!Array<!proto.pb.Truck>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.Truck, 3));
};


/**
 * @param {!Array<!proto.pb.Truck>} value
 * @return {!proto.pb.OperationAssignmentUnit} returns this
*/
proto.pb.OperationAssignmentUnit.prototype.setTruckList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.pb.Truck=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.Truck}
 */
proto.pb.OperationAssignmentUnit.prototype.addTruck = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.pb.Truck, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.OperationAssignmentUnit} returns this
 */
proto.pb.OperationAssignmentUnit.prototype.clearTruckList = function() {
  return this.setTruckList([]);
};


/**
 * optional Upload upload = 4;
 * @return {?proto.pb.Upload}
 */
proto.pb.OperationAssignmentUnit.prototype.getUpload = function() {
  return /** @type{?proto.pb.Upload} */ (
    jspb.Message.getWrapperField(this, proto_entities_load_pb.Upload, 4));
};


/**
 * @param {?proto.pb.Upload|undefined} value
 * @return {!proto.pb.OperationAssignmentUnit} returns this
*/
proto.pb.OperationAssignmentUnit.prototype.setUpload = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.OperationAssignmentUnit} returns this
 */
proto.pb.OperationAssignmentUnit.prototype.clearUpload = function() {
  return this.setUpload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.OperationAssignmentUnit.prototype.hasUpload = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Download download = 5;
 * @return {?proto.pb.Download}
 */
proto.pb.OperationAssignmentUnit.prototype.getDownload = function() {
  return /** @type{?proto.pb.Download} */ (
    jspb.Message.getWrapperField(this, proto_entities_load_pb.Download, 5));
};


/**
 * @param {?proto.pb.Download|undefined} value
 * @return {!proto.pb.OperationAssignmentUnit} returns this
*/
proto.pb.OperationAssignmentUnit.prototype.setDownload = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.OperationAssignmentUnit} returns this
 */
proto.pb.OperationAssignmentUnit.prototype.clearDownload = function() {
  return this.setDownload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.OperationAssignmentUnit.prototype.hasDownload = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Shift shift = 6;
 * @return {!proto.pb.OperationAssignmentUnit.Shift}
 */
proto.pb.OperationAssignmentUnit.prototype.getShift = function() {
  return /** @type {!proto.pb.OperationAssignmentUnit.Shift} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.pb.OperationAssignmentUnit.Shift} value
 * @return {!proto.pb.OperationAssignmentUnit} returns this
 */
proto.pb.OperationAssignmentUnit.prototype.setShift = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional State state = 7;
 * @return {!proto.pb.OperationAssignmentUnit.State}
 */
proto.pb.OperationAssignmentUnit.prototype.getState = function() {
  return /** @type {!proto.pb.OperationAssignmentUnit.State} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.pb.OperationAssignmentUnit.State} value
 * @return {!proto.pb.OperationAssignmentUnit} returns this
 */
proto.pb.OperationAssignmentUnit.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.Truck.repeatedFields_ = [14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.Truck.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.Truck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.Truck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.Truck.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    deviceId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    deviceAlias: jspb.Message.getFieldWithDefault(msg, 3, ""),
    deviceInterval: jspb.Message.getFieldWithDefault(msg, 4, 0),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    plate: jspb.Message.getFieldWithDefault(msg, 6, ""),
    hourmeter: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    contractor: (f = msg.getContractor()) && proto_entities_contractor_pb.Contractor.toObject(includeInstance, f),
    state: jspb.Message.getFieldWithDefault(msg, 9, 0),
    eventState: (f = msg.getEventState()) && proto_entities_event_state_pb.EventState.toObject(includeInstance, f),
    sensor: (f = msg.getSensor()) && proto_entities_sensor_pb.Sensor.toObject(includeInstance, f),
    realInterval: jspb.Message.getFieldWithDefault(msg, 12, 0),
    cycleNumber: jspb.Message.getFieldWithDefault(msg, 13, 0),
    operationList: jspb.Message.toObjectList(msg.getOperationList(),
    proto.pb.OperationAssignmentUnit.toObject, includeInstance),
    tonne: jspb.Message.getFloatingPointFieldWithDefault(msg, 15, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.Truck}
 */
proto.pb.Truck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.Truck;
  return proto.pb.Truck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.Truck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.Truck}
 */
proto.pb.Truck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceAlias(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDeviceInterval(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlate(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHourmeter(value);
      break;
    case 8:
      var value = new proto_entities_contractor_pb.Contractor;
      reader.readMessage(value,proto_entities_contractor_pb.Contractor.deserializeBinaryFromReader);
      msg.setContractor(value);
      break;
    case 9:
      var value = /** @type {!proto.pb.EnumEventState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 10:
      var value = new proto_entities_event_state_pb.EventState;
      reader.readMessage(value,proto_entities_event_state_pb.EventState.deserializeBinaryFromReader);
      msg.setEventState(value);
      break;
    case 11:
      var value = new proto_entities_sensor_pb.Sensor;
      reader.readMessage(value,proto_entities_sensor_pb.Sensor.deserializeBinaryFromReader);
      msg.setSensor(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRealInterval(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCycleNumber(value);
      break;
    case 14:
      var value = new proto.pb.OperationAssignmentUnit;
      reader.readMessage(value,proto.pb.OperationAssignmentUnit.deserializeBinaryFromReader);
      msg.addOperation(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setTonne(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.Truck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.Truck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.Truck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.Truck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDeviceId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDeviceAlias();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDeviceInterval();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPlate();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getHourmeter();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getContractor();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto_entities_contractor_pb.Contractor.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getEventState();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto_entities_event_state_pb.EventState.serializeBinaryToWriter
    );
  }
  f = message.getSensor();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto_entities_sensor_pb.Sensor.serializeBinaryToWriter
    );
  }
  f = message.getRealInterval();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getCycleNumber();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getOperationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto.pb.OperationAssignmentUnit.serializeBinaryToWriter
    );
  }
  f = message.getTonne();
  if (f !== 0.0) {
    writer.writeFloat(
      15,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.pb.Truck.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string device_id = 2;
 * @return {string}
 */
proto.pb.Truck.prototype.getDeviceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setDeviceId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string device_alias = 3;
 * @return {string}
 */
proto.pb.Truck.prototype.getDeviceAlias = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setDeviceAlias = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 device_interval = 4;
 * @return {number}
 */
proto.pb.Truck.prototype.getDeviceInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setDeviceInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.pb.Truck.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string plate = 6;
 * @return {string}
 */
proto.pb.Truck.prototype.getPlate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setPlate = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional float hourmeter = 7;
 * @return {number}
 */
proto.pb.Truck.prototype.getHourmeter = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setHourmeter = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional Contractor contractor = 8;
 * @return {?proto.pb.Contractor}
 */
proto.pb.Truck.prototype.getContractor = function() {
  return /** @type{?proto.pb.Contractor} */ (
    jspb.Message.getWrapperField(this, proto_entities_contractor_pb.Contractor, 8));
};


/**
 * @param {?proto.pb.Contractor|undefined} value
 * @return {!proto.pb.Truck} returns this
*/
proto.pb.Truck.prototype.setContractor = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.clearContractor = function() {
  return this.setContractor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.Truck.prototype.hasContractor = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional EnumEventState state = 9;
 * @return {!proto.pb.EnumEventState}
 */
proto.pb.Truck.prototype.getState = function() {
  return /** @type {!proto.pb.EnumEventState} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.pb.EnumEventState} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional EventState event_state = 10;
 * @return {?proto.pb.EventState}
 */
proto.pb.Truck.prototype.getEventState = function() {
  return /** @type{?proto.pb.EventState} */ (
    jspb.Message.getWrapperField(this, proto_entities_event_state_pb.EventState, 10));
};


/**
 * @param {?proto.pb.EventState|undefined} value
 * @return {!proto.pb.Truck} returns this
*/
proto.pb.Truck.prototype.setEventState = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.clearEventState = function() {
  return this.setEventState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.Truck.prototype.hasEventState = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Sensor sensor = 11;
 * @return {?proto.pb.Sensor}
 */
proto.pb.Truck.prototype.getSensor = function() {
  return /** @type{?proto.pb.Sensor} */ (
    jspb.Message.getWrapperField(this, proto_entities_sensor_pb.Sensor, 11));
};


/**
 * @param {?proto.pb.Sensor|undefined} value
 * @return {!proto.pb.Truck} returns this
*/
proto.pb.Truck.prototype.setSensor = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.clearSensor = function() {
  return this.setSensor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.Truck.prototype.hasSensor = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional uint32 real_interval = 12;
 * @return {number}
 */
proto.pb.Truck.prototype.getRealInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setRealInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int64 cycle_number = 13;
 * @return {number}
 */
proto.pb.Truck.prototype.getCycleNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setCycleNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * repeated OperationAssignmentUnit operation = 14;
 * @return {!Array<!proto.pb.OperationAssignmentUnit>}
 */
proto.pb.Truck.prototype.getOperationList = function() {
  return /** @type{!Array<!proto.pb.OperationAssignmentUnit>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.OperationAssignmentUnit, 14));
};


/**
 * @param {!Array<!proto.pb.OperationAssignmentUnit>} value
 * @return {!proto.pb.Truck} returns this
*/
proto.pb.Truck.prototype.setOperationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.pb.OperationAssignmentUnit=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.OperationAssignmentUnit}
 */
proto.pb.Truck.prototype.addOperation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.pb.OperationAssignmentUnit, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.clearOperationList = function() {
  return this.setOperationList([]);
};


/**
 * optional float tonne = 15;
 * @return {number}
 */
proto.pb.Truck.prototype.getTonne = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 15, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pb.Truck} returns this
 */
proto.pb.Truck.prototype.setTonne = function(value) {
  return jspb.Message.setProto3FloatField(this, 15, value);
};


goog.object.extend(exports, proto.pb);
