// source: proto/entities/yellow_machinery.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_entities_asset_type_pb = require('../../proto/entities/asset_type_pb.js');
goog.object.extend(proto, proto_entities_asset_type_pb);
var proto_enums_asset_type_enums_pb = require('../../proto/enums/asset_type.enums_pb.js');
goog.object.extend(proto, proto_enums_asset_type_enums_pb);
goog.exportSymbol('proto.pb.YellowMachinery', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.YellowMachinery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.YellowMachinery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.YellowMachinery.displayName = 'proto.pb.YellowMachinery';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.YellowMachinery.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.YellowMachinery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.YellowMachinery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.YellowMachinery.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    deviceId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    deviceAlias: jspb.Message.getFieldWithDefault(msg, 3, ""),
    deviceInterval: jspb.Message.getFieldWithDefault(msg, 4, 0),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    plate: jspb.Message.getFieldWithDefault(msg, 6, ""),
    hourmeter: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    assetType: (f = msg.getAssetType()) && proto_entities_asset_type_pb.AssetType.toObject(includeInstance, f),
    enumAssetType: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.YellowMachinery}
 */
proto.pb.YellowMachinery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.YellowMachinery;
  return proto.pb.YellowMachinery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.YellowMachinery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.YellowMachinery}
 */
proto.pb.YellowMachinery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceAlias(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDeviceInterval(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlate(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHourmeter(value);
      break;
    case 8:
      var value = new proto_entities_asset_type_pb.AssetType;
      reader.readMessage(value,proto_entities_asset_type_pb.AssetType.deserializeBinaryFromReader);
      msg.setAssetType(value);
      break;
    case 9:
      var value = /** @type {!proto.pb.EnumAssetType} */ (reader.readEnum());
      msg.setEnumAssetType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.YellowMachinery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.YellowMachinery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.YellowMachinery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.YellowMachinery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDeviceId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDeviceAlias();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDeviceInterval();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPlate();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getHourmeter();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getAssetType();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto_entities_asset_type_pb.AssetType.serializeBinaryToWriter
    );
  }
  f = message.getEnumAssetType();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.pb.YellowMachinery.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string device_id = 2;
 * @return {string}
 */
proto.pb.YellowMachinery.prototype.getDeviceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setDeviceId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string device_alias = 3;
 * @return {string}
 */
proto.pb.YellowMachinery.prototype.getDeviceAlias = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setDeviceAlias = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 device_interval = 4;
 * @return {number}
 */
proto.pb.YellowMachinery.prototype.getDeviceInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setDeviceInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.pb.YellowMachinery.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string plate = 6;
 * @return {string}
 */
proto.pb.YellowMachinery.prototype.getPlate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setPlate = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional float hourmeter = 7;
 * @return {number}
 */
proto.pb.YellowMachinery.prototype.getHourmeter = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setHourmeter = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional AssetType asset_type = 8;
 * @return {?proto.pb.AssetType}
 */
proto.pb.YellowMachinery.prototype.getAssetType = function() {
  return /** @type{?proto.pb.AssetType} */ (
    jspb.Message.getWrapperField(this, proto_entities_asset_type_pb.AssetType, 8));
};


/**
 * @param {?proto.pb.AssetType|undefined} value
 * @return {!proto.pb.YellowMachinery} returns this
*/
proto.pb.YellowMachinery.prototype.setAssetType = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.clearAssetType = function() {
  return this.setAssetType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pb.YellowMachinery.prototype.hasAssetType = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional EnumAssetType enum_asset_type = 9;
 * @return {!proto.pb.EnumAssetType}
 */
proto.pb.YellowMachinery.prototype.getEnumAssetType = function() {
  return /** @type {!proto.pb.EnumAssetType} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.pb.EnumAssetType} value
 * @return {!proto.pb.YellowMachinery} returns this
 */
proto.pb.YellowMachinery.prototype.setEnumAssetType = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


goog.object.extend(exports, proto.pb);
